[project]
name = "afdb-toolkit"
version = "0.1.0"
description = "A comprehensive toolkit for integrating structural models into the AlphaFold Database (AFDB)."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gemmi>=0.7.3",
    "jsonschema>=4.24.0",
    "numpy>=2.3.1",
    "requests>=2.32.4",
    "typer>=0.16.0",
]

[dependency-groups]
dev = [
    "coverage>=7.9.2",
    "flake8>=7.3.0",
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
]
docs = [
    "furo>=2024.8.6",
    "sphinx>=8.2.3",
    "sphinx-autodoc-typehints>=3.2.0",
]
